### ISSUE TITLE
Segmentation fault (core dumped)内存溢出错误？

### ISSUE THREAD

**Issue by topDreamer** [xiaolalala/Chinese-NER#1]
您好！感谢分享源码！我直接运行程序，会报错，报错信息如下，请问这种怎么解决呢？
![image](https://user-images.githubusercontent.com/29766163/85198376-d3abe180-b31a-11ea-8246-8d0ccc05fb9a.png)

**Comment by xiaofei05** [comment]
可能pytorch版本不对应？我这边在pytorch==1.5.0测试了下没有问题。
