### ISSUE TITLE
关于data下json文件

### ISSUE THREAD

**Issue by yt-liang** [xiaolalala/Chinese-NER#3]
您好，想问一下，使用您的数据，json文件可以直接使用github中data中的吗，还是需要自己制作

**Comment by xiaofei05** [comment]
data文件夹里的 train.txt/dev.txt/... 只有几条样例数据，你可以从 ReadMe - Preparation - Data Format 里给出的那个网盘链接下载所有的数据，放在data/renminribao2014/下，执行下脚本 python process_rmrb.py 即可处理得到所有数据的txt文件。

**Comment by YuniverseLab** [comment]
> data文件夹里的 train.txt/dev.txt/... 只有几条样例数据，你可以从 ReadMe - Preparation - Data Format 里给出的那个网盘链接下载所有的数据，放在data/renminribao2014/下，执行下脚本 python process_rmrb.py 即可处理得到所有数据的txt文件。

对的，我已经从百度网盘下载下来了，我看需要一个json文件，这个直接用github上的就行是吗？train之后，运行test，结果是直接就得到准确率了是吗，还是需要自己计算？

**Comment by xiaofei05** [comment]
执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
运行程序会自动得到所有的准确率。

**Comment by YuniverseLab** [comment]
> 执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
> 运行程序会自动得到所有的准确率。

好的，谢谢您，现在刚刚学，还没有入门，想找一个学习，我觉得您的挺好，想看跑通了，就读一读代码。gpu需要一般多久呀，cpu我看很慢，再次谢谢您了。

**Comment by YuniverseLab** [comment]
> 执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
> 运行程序会自动得到所有的准确率。

![image](https://user-images.githubusercontent.com/58623131/88519169-46982e80-d024-11ea-84ed-3b67fde56a09.png)
这个是刚刚电脑训练了一点，出来的结果，您看是这样吗

**Comment by YuniverseLab** [comment]
> 执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
> 运行程序会自动得到所有的准确率。

![image](https://user-images.githubusercontent.com/58623131/88519319-8101cb80-d024-11ea-93de-de85fbf268a5.png)

**Comment by xiaofei05** [comment]
> > 执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
> > 运行程序会自动得到所有的准确率。
> 
> 好的，谢谢您，现在刚刚学，还没有入门，想找一个学习，我觉得您的挺好，想看跑通了，就读一读代码。gpu需要一般多久呀，cpu我看很慢，再次谢谢您了。

看GPU型号，一般10倍以上，具体可以百度一下。

**Comment by YuniverseLab** [comment]
> > > 执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
> > > 运行程序会自动得到所有的准确率。
> > 
> > 
> > 好的，谢谢您，现在刚刚学，还没有入门，想找一个学习，我觉得您的挺好，想看跑通了，就读一读代码。gpu需要一般多久呀，cpu我看很慢，再次谢谢您了。
> 
> 看GPU型号，一般10倍以上，具体可以百度一下。

好的，谢谢您了

**Comment by YuniverseLab** [comment]
> > > 执行完python process_rmrb.py会自动得到word2id.json，这个文件只有在LSTM（+CRF）的时候会被使用。
> > > 运行程序会自动得到所有的准确率。
> > 
> > 
> > 好的，谢谢您，现在刚刚学，还没有入门，想找一个学习，我觉得您的挺好，想看跑通了，就读一读代码。gpu需要一般多久呀，cpu我看很慢，再次谢谢您了。
> 
> 看GPU型号，一般10倍以上，具体可以百度一下。

![image](https://user-images.githubusercontent.com/58623131/88522915-afce7080-d029-11ea-9115-bdd1bd163975.png)
您好，训练出现了错误

**Comment by YuniverseLab** [comment]
![image](https://user-images.githubusercontent.com/58623131/88525368-1608c280-d02d-11ea-8768-ab05c517531e.png)
就是一个epoch还没训练完这里，直接报错了，我就运行了一下数据的那个文件，其它都没有修改

**Comment by xiaofei05** [comment]
> ![image](https://user-images.githubusercontent.com/58623131/88525368-1608c280-d02d-11ea-8768-ab05c517531e.png)
> 就是一个epoch还没训练完这里，直接报错了，我就运行了一下数据的那个文件，其它都没有修改

应该是读数据的时候空行没有处理。更新了dataloader.py，你pull一下最新的再试一下

**Comment by dinobby** [comment]
百度網盤的連結好像已經失效了，不知道有沒有好心人能夠提供一下人民日報2014資料集呢？非常感謝
